### ISSUE TITLE
Should we drop the ScientificTypes dependency?

### ISSUE THREAD

**Issue by jbrea** [JuliaAI/OpenML.jl#12]
In the current version `ScientificTypes` are only used for an almost trivial [one-liner](https://github.com/JuliaAI/OpenML.jl/blob/dev/src/data.jl#L78) that one could mention in the doc-string.
@ablaom In the spirit of keeping this package lightweight and independent of the MLJ universe, do you think it would make sense to remove the `parser = :auto` option and drop this dependency?

**Comment by ablaom** [comment]
I agree. This is better design. 

Breaking, but that's fine.
